const statesData = {
    "texas": "Texas",
    "california": "California",
    "newyork": "New York",
    "vermont": "Vermont",
    "newhampshire": "New Hampshire",
    "maine": "Maine",
    "rhodeisland": "Rhode Island",
    "massachusetts": "Massachusetts",
    "connecticut": "Connecticut",
    "newjersey": "New Jersey",
    "pennsylvania": "Pennsylvania",
    "ohio": "Ohio",
    "westvirginia": "West Virginia",
    "virginia": "Virginia",
    "delaware": "Delaware",
    "maryland": "Maryland",
    "southcarolina": "South Carolina",
    "northcarolina": "North Carolina",
    "kentucky": "Kentucky",
    "tennessee": "Tennessee",
    "georgia": "Georgia",
    "florida": "Florida",
    "alabama": "Alabama",
    "mississippi": "Mississippi",
    "louisiana": "Louisiana",
    "arkansas": "Arkansas",
    "missouri": "Missouri",
    "illinois": "Illinois",
    "indiana": "Indiana",
    "michigan": "Michigan",
    "wisconsin": "Wisconsin",
    "minnesota": "Minnesota",
    "iowa": "Iowa",
    "northdakota": "North Dakota",
    "southdakota": "South Dakota",
    "nebraska": "Nebraska",
    "kansas": "Kansas",
    "oklahoma": "Oklahoma",
    "newmexico": "New Mexico",
    "colorado": "Colorado",
    "wyoming": "Wyoming",
    "montana": "Montana",
    "idaho": "Idaho",
    "utah": "Utah",
    "arizona": "Arizona",
    "nevada": "Nevada",
    "oregan": "Oregan",
    "washington": "Washington",
    "alaska": "Alaska",
    "hawaii": "Hawaii",
    "washingtondc": "Washington, DC",
    "placeholderBoolean": false
};